// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMYX8GOZuYwPRoBB33aZQrcPVvUt3dmec',
    appId: '1:872448584521:web:1a493529d8bec57588c898',
    messagingSenderId: '872448584521',
    projectId: 'pcnos-fbdbb',
    authDomain: 'pcnos-fbdbb.firebaseapp.com',
    storageBucket: 'pcnos-fbdbb.firebasestorage.app',
    measurementId: 'G-1C3T595WCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1E1ypqRZtvNaEKtIWeRj142vOhXU-1Rs',
    appId: '1:872448584521:android:ca61d76ce964ddd188c898',
    messagingSenderId: '872448584521',
    projectId: 'pcnos-fbdbb',
    storageBucket: 'pcnos-fbdbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcqX2rprOMRoi9yY-tsoAjmVHj82JYZik',
    appId: '1:872448584521:ios:c9cb05d2d0f1914a88c898',
    messagingSenderId: '872448584521',
    projectId: 'pcnos-fbdbb',
    storageBucket: 'pcnos-fbdbb.firebasestorage.app',
    iosBundleId: 'com.example.pcNos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcqX2rprOMRoi9yY-tsoAjmVHj82JYZik',
    appId: '1:872448584521:ios:c9cb05d2d0f1914a88c898',
    messagingSenderId: '872448584521',
    projectId: 'pcnos-fbdbb',
    storageBucket: 'pcnos-fbdbb.firebasestorage.app',
    iosBundleId: 'com.example.pcNos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMYX8GOZuYwPRoBB33aZQrcPVvUt3dmec',
    appId: '1:872448584521:web:1353a35338617bc788c898',
    messagingSenderId: '872448584521',
    projectId: 'pcnos-fbdbb',
    authDomain: 'pcnos-fbdbb.firebaseapp.com',
    storageBucket: 'pcnos-fbdbb.firebasestorage.app',
    measurementId: 'G-56MMZWBZ1W',
  );
}
